name: Day 27 - Reusable Matrix Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy-matrix:
    strategy:
      matrix:
        env: [dev, staging, production]

    uses: ./.github/workflows/reusable-matrix.yml
    with:
      environment: ${{ matrix.env }}
    secrets:
      api-token: ${{ secrets.MY_SECRET_TOKEN }}